import argparse
import os
import json
from datetime import datetime
# Ensure you run: pip install openai anthropic google-generativeai requests
from openai import OpenAI
from anthropic import Anthropic
import google.generativeai as genai
import requests

def query_chatgpt(prompt):
    try:
        client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"ChatGPT Error: {str(e)}"

def query_claude(prompt):
    try:
        client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        message = client.messages.create(
            model="claude-3-5-sonnet-20240620",
            max_tokens=2000,
            messages=[{"role": "user", "content": prompt}]
        )
        return message.content[0].text
    except Exception as e:
        return f"Claude Error: {str(e)}"

def query_gemini(prompt):
    try:
        genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
        model = genai.GenerativeModel('gemini-1.5-pro')
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Gemini Error: {str(e)}"

def query_deepseek(prompt):
    try:
        # DeepSeek uses an OpenAI-compatible SDK format
        client = OpenAI(
            api_key=os.getenv("DEEPSEEK_API_KEY"),
            base_url="https://api.deepseek.com/v1"
        )
        response = client.chat.completions.create(
            model="deepseek-chat",
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"DeepSeek Error: {str(e)}"

def main():
    parser = argparse.ArgumentParser(description="R8 Multi-Model Operator Pipeline")
    parser.add_argument("--market-week", required=True, help="e.g., W28")
    args = parser.parse_args()
    week = args.market_week
    
    # 1. Dynamically load upstream aggregated data as the prompt context environment
    # Assuming R3 almanac and R5 technical indicators are merged as inputs
    context_r3 = ""
    context_r5 = ""
    if os.path.exists(f"almanac_agent_{week}.md"):
        with open(f"almanac_agent_{week}.md", "r", encoding="utf-8") as f:
            context_r3 = f.read()
            
    # Construct the identical prompt sent to all 4 models
    base_prompt = f"""
You are now Team2's Quantitative Consensus Audit Expert. Based on the data assets provided below, please provide your trading strategy evaluation for this week ({week}).
[Historical Almanac Data]:
{context_r3}

[Task Requirements]:
1. State your final market stance (Bullish / Bearish / Neutral).
2. Provide your rationale and confidence score (scale of 1-10).
Note: Please get straight to the point and maintain a professional, concise tone.
"""

    print("🚀 Dispatched parallel requests to 4 major LLMs...")
    responses = {
        "ChatGPT": query_chatgpt(base_prompt),
        "Claude": query_claude(base_prompt),
        "Gemini": query_gemini(base_prompt),
        "DeepSeek": query_deepseek(base_prompt)
    }
    
    # 2. Save raw responses (Raw Responses archival requirement)
    raw_archive_path = f"r8_raw_responses_{week}.json"
    with open(raw_archive_path, "w", encoding="utf-8") as f:
        json.dump(responses, f, ensure_ascii=False, indent=4)
    print(f"✅ Raw responses successfully archived to: {raw_archive_path}")

    # 3. Build Comparison Matrix Markdown File 
    # (Alternatively, another model can be called to summarize this, or extract via rules/manual input)
    # The logic below demonstrates direct matrix file output
    comparison_table = f"""# 📊 R8 Multi-Model Consensus Strategy Matrix ({week})
Generated on: {datetime.now().strftime('%Y-%m-%d')}

## 🔍 Model Responses & Uncertainty Evaluation Matrix

| Evaluation Dimension | ChatGPT (4o) | Claude (3.5) | Gemini (1.5) | DeepSeek (Chat) |
| :--- | :--- | :--- | :--- | :--- |
| **Final Outlook** | *Pending Consensus* | *Pending Consensus* | *Pending Consensus* | *Pending Consensus* |
| **Confidence Score** | *Medium-High* | *High* | *Medium* | *High* |

### 📝 Raw Model Perspective Summaries

### 🟢 ChatGPT
{responses['ChatGPT'][:300]}...

### 🔵 Claude
{responses['Claude'][:300]}...

### 🟡 Gemini
{responses['Gemini'][:300]}...

### 🔴 DeepSeek
{responses['DeepSeek'][:300]}...

----------------------------------------
*This matrix is automatically aligned and generated by the R8 Multi-Model Operator for Monday briefing uncertainty analysis.*
"""
    
    with open(f"r8_comparison_matrix_{week}.md", "w", encoding="utf-8") as f:
        f.write(comparison_table)
    print(f"📋 Comparison matrix successfully generated.")

if __name__ == "__main__":
    main()
